name: Industrialisation continue sur le serveur Alwaysdata

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Test SSH Connection
      run: |
        echo "Testing SSH connection to the server..."
        sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@ssh-${{ secrets.USERNAME }}.alwaysdata.net 'echo "SSH connection successful!"'

    - name: Connexion SSH avec le serveur
      uses: appleboy/ssh-action@master
      with:
        host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd $HOME/www/
          git pull origin main

    - name: Copy files to server
      uses: appleboy/ssh-action@master
      with:
        host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          last_directory=$(basename ${{ runner.workspace }})
          cd $HOME/
          git clone https://github.com/${{ github.repository }}.git
          if [ "$(ls -A ./www)" ]; then
            rsync -r ./$last_directory/ ./www
            rm -rf ./$last_directory
          else
            echo "Le répertoire flask de destination sur votre serveur n'existe pas"
            exit 1
